export class EnqueueNaturalPersonCreditApplicationRequest {
  constructor(
    readonly partnerId: string,
    readonly salesRepId: string,
    readonly firstName: string,
    readonly lastName: string,
    readonly docType: string,
    readonly docNumber: string,
    readonly phone: string | null,
    readonly email: string | null,
    readonly birthDate: string | null,
    readonly cityId: string | null,
    readonly businessType: string,
    readonly businessName: string | null,
    readonly businessAddress: string | null,
    readonly relationshipToBusiness: string | null,
    readonly businessSeniority: string | null,
    readonly numberOfEmployees: number | null,
    readonly numberOfLocations: number | null,
    readonly businessFlagshipM2: number | null,
    readonly businessHasRent: boolean | null,
    readonly businessRentAmount: number | null,
    readonly requestedCreditLine: number,
    readonly monthlyPurchases: number | null,
    readonly currentPurchases: number | null,
    readonly totalAssets: number | null,
    readonly monthlyIncome: number | null,
    readonly monthlyExpenses: number | null,
    readonly privacyPolicyAccepted: boolean,
    readonly idempotencyKey?: string | null,
  ) {}
}
