export const USER_REPOSITORY = Symbol('USER_REPOSITORY');

export const COGNITO_USER_PROVISIONING_PORT = Symbol('COGNITO_USER_PROVISIONING_PORT');

export const PARTNER_LINK_READER = Symbol('PARTNER_LINK_READER');

