// --- Repositorios ---
export const CREDIT_APPLICATION_REPOSITORY = Symbol('CREDIT_APPLICATION_REPOSITORY');
export const CREDIT_APPLICATION_JOB_REPOSITORY = Symbol('CREDIT_APPLICATION_JOB_REPOSITORY');
export const SARLAFT_CHECK_REPOSITORY = Symbol('SARLAFT_CHECK_REPOSITORY');
export const WEB_QUERY_REPOSITORY = Symbol('WEB_QUERY_REPOSITORY');
export const EXPERIAN_QUERY_REPOSITORY = Symbol('EXPERIAN_QUERY_REPOSITORY');
export const AI_AGENT_ANALYSIS_REPOSITORY = Symbol('AI_AGENT_ANALYSIS_REPOSITORY');

// --- Servicios externos ---
export const REMINDER_SCHEDULER_PORT = Symbol('REMINDER_SCHEDULER_PORT');
export const SARLAFT_SERVICE = Symbol('SARLAFT_SERVICE');
export const WEB_SCRAPING_SERVICE = Symbol('WEB_SCRAPING_SERVICE');
export const EXPERIAN_SERVICE = Symbol('EXPERIAN_SERVICE');
export const AI_AGENT_SERVICE = Symbol('AI_AGENT_SERVICE');
export const GOOGLE_CHAT_NOTIFIER = Symbol('GOOGLE_CHAT_NOTIFIER');
