export const STORAGE_PORT = Symbol('STORAGE_PORT');
export const REMOTE_FILE_FETCH_PORT = Symbol('REMOTE_FILE_FETCH_PORT');
export const UPLOAD_FILES_IDEMPOTENCY_PORT = Symbol('UPLOAD_FILES_IDEMPOTENCY_PORT');
