export const STORAGE_PORT = Symbol('STORAGE_PORT');
export const REMOTE_FILE_FETCH_PORT = Symbol('REMOTE_FILE_FETCH_PORT');
export const UPLOAD_FILES_IDEMPOTENCY_PORT = Symbol('UPLOAD_FILES_IDEMPOTENCY_PORT');
export const PARTNER_CREATE_USER_SQS_IDEMPOTENCY_PORT = Symbol(
  'PARTNER_CREATE_USER_SQS_IDEMPOTENCY_PORT',
);
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const CITY_REPOSITORY = Symbol('CITY_REPOSITORY');
export const STATUS_REPOSITORY = Symbol('STATUS_REPOSITORY');
export const CURRENCY_READ_PORT = Symbol('CURRENCY_READ_PORT');
