export interface CreditApplicationBnplProps {
  id: number;
  externalId: string;
  userId: number;
  userProductId: number | null;
  partnerId: number | null;
  partnerCategoryId: number | null;
  salesRepId: number | null;
  businessId: number | null;
  numberOfLocations: number | null;
  numberOfEmployees: number | null;
  businessSeniorityId: number | null;
  sectorExperience: string | null;
  businessFlagshipM2: number | null;
  businessHasRent: boolean | null;
  businessRentAmount: number | null;
  monthlyIncome: number | null;
  monthlyExpenses: number | null;
  monthlyPurchases: number | null;
  currentPurchases: number | null;
  totalAssets: number | null;
  requestedCreditLine: number | null;
  isCurrentClient: boolean;
  statusId: number;
  submissionDate: Date | null;
  approvalDate: Date | null;
  rejectionReason: string | null;
  creditStudyDate: Date | null;
  creditScore: string | null;
  creditDecision: string | null;
  approvedCreditLine: number | null;
  analystReport: string | null;
  riskProfile: string | null;
  privacyPolicyAccepted: boolean;
  privacyPolicyDate: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export class CreditApplicationBnpl {
  public readonly id: number;
  public readonly externalId: string;
  public readonly userId: number;
  public readonly userProductId: number | null;
  public readonly partnerId: number | null;
  public readonly partnerCategoryId: number | null;
  public readonly salesRepId: number | null;
  public readonly businessId: number | null;
  public readonly numberOfLocations: number | null;
  public readonly numberOfEmployees: number | null;
  public readonly businessSeniorityId: number | null;
  public readonly sectorExperience: string | null;
  public readonly businessFlagshipM2: number | null;
  public readonly businessHasRent: boolean | null;
  public readonly businessRentAmount: number | null;
  public readonly monthlyIncome: number | null;
  public readonly monthlyExpenses: number | null;
  public readonly monthlyPurchases: number | null;
  public readonly currentPurchases: number | null;
  public readonly totalAssets: number | null;
  public readonly requestedCreditLine: number | null;
  public readonly isCurrentClient: boolean;
  public readonly statusId: number;
  public readonly submissionDate: Date | null;
  public readonly approvalDate: Date | null;
  public readonly rejectionReason: string | null;
  public readonly creditStudyDate: Date | null;
  public readonly creditScore: string | null;
  public readonly creditDecision: string | null;
  public readonly approvedCreditLine: number | null;
  public readonly analystReport: string | null;
  public readonly riskProfile: string | null;
  public readonly privacyPolicyAccepted: boolean;
  public readonly privacyPolicyDate: Date | null;
  public readonly createdAt: Date;
  public readonly updatedAt: Date;

  constructor(props: CreditApplicationBnplProps) {
    this.id = props.id;
    this.externalId = props.externalId;
    this.userId = props.userId;
    this.userProductId = props.userProductId;
    this.partnerId = props.partnerId;
    this.partnerCategoryId = props.partnerCategoryId;
    this.salesRepId = props.salesRepId;
    this.businessId = props.businessId;
    this.numberOfLocations = props.numberOfLocations;
    this.numberOfEmployees = props.numberOfEmployees;
    this.businessSeniorityId = props.businessSeniorityId;
    this.sectorExperience = props.sectorExperience;
    this.businessFlagshipM2 = props.businessFlagshipM2;
    this.businessHasRent = props.businessHasRent;
    this.businessRentAmount = props.businessRentAmount;
    this.monthlyIncome = props.monthlyIncome;
    this.monthlyExpenses = props.monthlyExpenses;
    this.monthlyPurchases = props.monthlyPurchases;
    this.currentPurchases = props.currentPurchases;
    this.totalAssets = props.totalAssets;
    this.requestedCreditLine = props.requestedCreditLine;
    this.isCurrentClient = props.isCurrentClient;
    this.statusId = props.statusId;
    this.submissionDate = props.submissionDate;
    this.approvalDate = props.approvalDate;
    this.rejectionReason = props.rejectionReason;
    this.creditStudyDate = props.creditStudyDate;
    this.creditScore = props.creditScore;
    this.creditDecision = props.creditDecision;
    this.approvedCreditLine = props.approvedCreditLine;
    this.analystReport = props.analystReport;
    this.riskProfile = props.riskProfile;
    this.privacyPolicyAccepted = props.privacyPolicyAccepted;
    this.privacyPolicyDate = props.privacyPolicyDate;
    this.createdAt = props.createdAt;
    this.updatedAt = props.updatedAt;
  }
}
