export interface OnboardingProps {
  id: number;
  externalId: string;
  userId: number;
  userProductId: number | null;
  partnerId: number | null;
  partnerCategoryId: number | null;
  salesRepId: number | null;
  businessName: string | null;
  businessRelationId: number | null;
  businessTypeName: string | null;
  businessTypeCode: number | null;
  businessAddress: string | null;
  businessCity: string | null;
  businessRentAmount: string | null;
  numberOfLocations: number | null;
  numberOfEmployees: number | null;
  businessSeniorityId: number | null;
  sectorExperience: string | null;
  relationshipToBusiness: string | null;
  monthlyIncome: string | null;
  monthlyExpenses: string | null;
  monthlyPurchases: string | null;
  currentPurchases: string | null;
  totalAssets: string | null;
  requestedCreditLine: string | null;
  isCurrentClient: boolean;
  statusId: number;
  submissionDate: Date | null;
  approvalDate: Date | null;
  rejectionReason: string | null;
  creditStudyDate: Date | null;
  creditScore: string | null;
  creditDecision: string | null;
  approvedCreditLine: string | null;
  analystReport: string | null;
  riskProfile: string | null;
  privacyPolicyAccepted: boolean;
  privacyPolicyDate: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export class Onboarding {
  public readonly id: number;
  public readonly externalId: string;
  public readonly userId: number;
  public readonly userProductId: number | null;
  public readonly partnerId: number | null;
  public readonly partnerCategoryId: number | null;
  public readonly salesRepId: number | null;
  public readonly businessName: string | null;
  public readonly businessRelationId: number | null;
  public readonly businessTypeName: string | null;
  public readonly businessTypeCode: number | null;
  public readonly businessAddress: string | null;
  public readonly businessCity: string | null;
  public readonly businessRentAmount: string | null;
  public readonly numberOfLocations: number | null;
  public readonly numberOfEmployees: number | null;
  public readonly businessSeniorityId: number | null;
  public readonly sectorExperience: string | null;
  public readonly relationshipToBusiness: string | null;
  public readonly monthlyIncome: string | null;
  public readonly monthlyExpenses: string | null;
  public readonly monthlyPurchases: string | null;
  public readonly currentPurchases: string | null;
  public readonly totalAssets: string | null;
  public readonly requestedCreditLine: string | null;
  public readonly isCurrentClient: boolean;
  public readonly statusId: number;
  public readonly submissionDate: Date | null;
  public readonly approvalDate: Date | null;
  public readonly rejectionReason: string | null;
  public readonly creditStudyDate: Date | null;
  public readonly creditScore: string | null;
  public readonly creditDecision: string | null;
  public readonly approvedCreditLine: string | null;
  public readonly analystReport: string | null;
  public readonly riskProfile: string | null;
  public readonly privacyPolicyAccepted: boolean;
  public readonly privacyPolicyDate: Date | null;
  public readonly createdAt: Date;
  public readonly updatedAt: Date;

  constructor(props: OnboardingProps) {
    this.id = props.id;
    this.externalId = props.externalId;
    this.userId = props.userId;
    this.userProductId = props.userProductId;
    this.partnerId = props.partnerId;
    this.partnerCategoryId = props.partnerCategoryId;
    this.salesRepId = props.salesRepId;
    this.businessName = props.businessName;
    this.businessRelationId = props.businessRelationId;
    this.businessTypeName = props.businessTypeName;
    this.businessTypeCode = props.businessTypeCode;
    this.businessAddress = props.businessAddress;
    this.businessCity = props.businessCity;
    this.businessRentAmount = props.businessRentAmount;
    this.numberOfLocations = props.numberOfLocations;
    this.numberOfEmployees = props.numberOfEmployees;
    this.businessSeniorityId = props.businessSeniorityId;
    this.sectorExperience = props.sectorExperience;
    this.relationshipToBusiness = props.relationshipToBusiness;
    this.monthlyIncome = props.monthlyIncome;
    this.monthlyExpenses = props.monthlyExpenses;
    this.monthlyPurchases = props.monthlyPurchases;
    this.currentPurchases = props.currentPurchases;
    this.totalAssets = props.totalAssets;
    this.requestedCreditLine = props.requestedCreditLine;
    this.isCurrentClient = props.isCurrentClient;
    this.statusId = props.statusId;
    this.submissionDate = props.submissionDate;
    this.approvalDate = props.approvalDate;
    this.rejectionReason = props.rejectionReason;
    this.creditStudyDate = props.creditStudyDate;
    this.creditScore = props.creditScore;
    this.creditDecision = props.creditDecision;
    this.approvedCreditLine = props.approvedCreditLine;
    this.analystReport = props.analystReport;
    this.riskProfile = props.riskProfile;
    this.privacyPolicyAccepted = props.privacyPolicyAccepted;
    this.privacyPolicyDate = props.privacyPolicyDate;
    this.createdAt = props.createdAt;
    this.updatedAt = props.updatedAt;
  }
}
