export class RegisterNaturalPersonCreditApplicationRequest {
  constructor(
    readonly birthDate: string | null | undefined,
    readonly businessAddress: string | null | undefined,
    readonly businessFlagshipM2: number | null | undefined,
    readonly businessName: string,
    readonly businessRentAmount: number | undefined,
    readonly businessSeniority: string | null | undefined,
    readonly businessType: string,
    readonly cityId: string | null | undefined,
    readonly currentPurchases: number | null | undefined,
    readonly docNumber: string,
    readonly docType: string,
    readonly email: string,
    readonly firstName: string,
    readonly lastName: string,
    readonly monthlyExpenses: number | null | undefined,
    readonly monthlyIncome: number | null | undefined,
    readonly monthlyPurchases: number | undefined,
    readonly numberOfEmployees: number | null | undefined,
    readonly numberOfLocations: number | null | undefined,
    readonly partnerId: string,
    readonly salesRepId: string,
    readonly privacyPolicyAccepted: boolean,
    readonly phone: string,
    readonly relationshipToBusiness: string | null | undefined,
    readonly requestedCreditLine: number,
    readonly totalAssets: number | null | undefined,
  ) {}
}
